[1/2] transcript model/graphql
bolt-foundry/bolt-foundry pull request #322
Opened 2024-08-06 18:21 UTC by justicart

[1/2] transcript model/graphql

Summary: Added BfTranscript model and BfGraphQLTranscript.
Added `delete` to Model and bfDb

Test Plan:

2024-08-06 23:45 UTC, ColbyBaker approved these changes

2024-08-07 01:43 UTC, randallb requested changes
Please use connections whenever linking throughout the graph.

2024-08-07 01:43 UTC, randallb commented on packages/bfDb/bfDb.ts
> +export async function bfDeleteItem(bfOid: BfOid, bfGid: BfGid): Promise<void> {
this is a pretty good idea. Using bfoid ensures a tiny bit of security... and I think that's about the right amount for now.

2024-08-07 01:43 UTC, randallb commented on packages/bfDb/classes/BfModel.ts
> +      log(`Deleted ${this.constructor.name} with bfOid: ${this.metadata.bfOid} and bfGid: ${this.metadata.bfGid}`);
this is a crappy logger... wouldn't encourage it's continued use.

2024-08-07 01:43 UTC, randallb commented on packages/bfDb/models/BfTranscript.ts
> +      className: 'BfTranscript',
this should not be necessary. Please don't do it unless there's a reason the fw didn't work w/o it.

2024-08-07 01:43 UTC, randallb commented on packages/graphql/types/BfGraphQLTranscript.ts
> +        const transcripts = await BfTranscript.findTranscriptsByViewer(bfCurrentViewer);
Please don't do this... it shouldn't be a field but instead a connection. It also should use `queryConnectionForGraphQL` so you don't even have to write any real code... just 
```typescript
BfTranscript.queryConnectionForGraphQL(bfCurrentViewer, {bfOid: bfCurrentViewer.bfOid}, {}, args)
```

Check out https://github.com/bolt-foundry/bolt-foundry/blob/main/packages/graphql/types/BfGraphQLClipReview.ts#L24 for more.

2024-08-07 02:05 UTC, randallb commented on packages/graphql/types/BfGraphQLTranscript.ts
> +        const transcripts = await BfTranscript.findTranscriptsByViewer(bfCurrentViewer);
Oh also use parent.id instead of current viewer so future connections work properly please.

2024-08-07 02:06 UTC, randallb commented on packages/graphql/types/BfGraphQLTranscript.ts
> +});
We could probably make a generic deleteNode mutation so we wouldn't have to have a ton of random delete mutations. IDK if that's worth thinking through now though.

2024-08-07 14:21 UTC, justicart commented on packages/bfDb/models/BfTranscript.ts
> +      className: 'BfTranscript',
It returned everything in the db owned by BF without it

2024-08-07 14:24 UTC, justicart commented on packages/graphql/types/BfGraphQLTranscript.ts
> +        const transcripts = await BfTranscript.findTranscriptsByViewer(bfCurrentViewer);
parent.id instead of bfOid?

2024-08-07 14:53 UTC, justicart commented on packages/bfDb/classes/BfModel.ts
> +      log(`Deleted ${this.constructor.name} with bfOid: ${this.metadata.bfOid} and bfGid: ${this.metadata.bfGid}`);
like, this is a crappy use of a log and remove it? Or use a different logger?

2024-08-07 15:00 UTC, justicart commented on packages/graphql/types/BfGraphQLTranscript.ts
> +        const transcripts = await BfTranscript.findTranscriptsByViewer(bfCurrentViewer);
I didn't make this a connection because when we talked about it, we weren't connecting transcripts to the organization

2024-08-07 16:28 UTC, randallb commented on packages/graphql/types/BfGraphQLTranscript.ts
> +        const transcripts = await BfTranscript.findTranscriptsByViewer(bfCurrentViewer);
> parent.id instead of bfOid?

ya-- it's a graphql object, ie the post .toGraphQL() version of the model.

2024-08-07 16:29 UTC, randallb commented on packages/graphql/types/BfGraphQLTranscript.ts
> +        const transcripts = await BfTranscript.findTranscriptsByViewer(bfCurrentViewer);
> I didn't make this a connection because when we talked about it, we weren't connecting transcripts to the organization

I think generally if you're going to connect two models together of any type they should be a relay connection.

2024-08-07 17:09 UTC, randallb commented on packages/bfDb/classes/BfModel.ts
> +      log(`Deleted ${this.constructor.name} with bfOid: ${this.metadata.bfOid} and bfGid: ${this.metadata.bfGid}`);
Use logger.debug or whatever.

2024-08-09 18:35 UTC, closed without merging