show nux when not authed
bolt-foundry/bolt-foundry pull request #432
Opened 2024-08-19 21:27 UTC by 19jlevitre

<img width="1512" alt="Screenshot 2024-08-19 at 3 28 02 PM" src="https://github.com/user-attachments/assets/b062f3b8-0720-4985-8fb4-64086efa725e">
<img width="1512" alt="Screenshot 2024-08-19 at 3 28 15 PM" src="https://github.com/user-attachments/assets/16a49aaf-cbe0-4c82-91c2-ba06d53aca34">

Summary:

Test Plan:

2024-08-19 21:37 UTC, randallb requested changes
It's a good idea to consider if the prop removals are a good idea... generally we want data to be loaded as close to the component as possible, not passed down into props. The exception, generally, is design system code. BfDs stuff should usually be mostly (if not always) without graphql.

2024-08-19 21:37 UTC, randallb commented on packages/client/components/clipsearch/Clip.tsx
> +    notAuthed
this is a bit weird... it feels like it should be a query on something else instead of a prop.

2024-08-19 21:37 UTC, randallb commented on packages/client/components/clipsearch/ClipsView.tsx
> +  console.log("data", data);
rm

2024-08-19 21:37 UTC, randallb commented on packages/client/components/clipsearch/ClipsView.tsx
> +          </div>
Feels redundant with the code right before it? Could maybe be extracted?

2024-08-19 21:37 UTC, randallb commented on packages/client/components/clipsearch/Search.tsx
> +  count: number;
I don't love adding this as a prop. Why did you remove the graphql? I'd rather just keep it as a fragment than wipe it out.

2024-08-20 13:21 UTC, 19jlevitre commented on packages/client/components/clipsearch/Search.tsx
> +  count: number;
@randallb I was pairing with justin and the fragment wasnt working so we opped for this instead

2024-08-20 13:24 UTC, merged