ui views: Table -> BfDsTable
bolt-foundry/bolt-foundry pull request #444
Opened 2024-08-20 19:14 UTC by mikesavior

Summary: change refs of Table to BfDsTable so that traversing the dom with react dev tools is easier to do

Test Plan: TBD

2024-08-20 19:45 UTC, justicart requested changes
Make sure to check the types Column and Columns where you changed the imports to BfDsColumn and BfDsColumns... they need to be changed in the code where they are used alos

2024-08-20 19:45 UTC, justicart commented on infra/internalbf.com/client/components/InternalMediaList.tsx
> +import { Column, BfDsTable } from "packages/bfDs/BfDsTable.tsx";
Column should be BfDsColumn

2024-08-20 19:45 UTC, justicart commented on infra/internalbf.com/client/components/InternalMediaList.tsx
>    {
Column should be BfDsColumn

2024-08-20 19:45 UTC, justicart commented on infra/internalbf.com/client/components/InternalProjectsList.tsx
>    {
Make sure you catch these Column types... Column -> BfDsColumn

2024-08-20 19:45 UTC, justicart commented on infra/internalbf.com/client/pages/ChangesPage.tsx
>  const columns: Array<Column<DataType>> = [
Column -> BfDsColumn

2024-08-20 19:45 UTC, justicart commented on infra/internalbf.com/client/pages/IBfOrganizationsPage.tsx
> +import { BfDsColumns, BfDsTable } from "packages/bfDs/BfDsTable.tsx";
Any time you change these "Columns" or "Column" types up here, make sure you change where they are used below

2024-08-20 19:45 UTC, justicart commented on packages/client/components/settings/Media.tsx
>      {
BfDsColumns

2024-08-20 19:45 UTC, justicart commented on packages/client/components/settings/WatchFolderList.tsx
>      {
BfDsColumns

2024-08-21 02:47 UTC, randallb submitted a review, later dismissed

2024-08-21 02:47 UTC, randallb commented on infra/internalbf.com/client/pages/ClipChangesPage.tsx
> +import { Table } from "packages/bfDs/BfDsTable.tsx";
This should be bfds table

2024-08-21 06:06 UTC, mikesavior commented on infra/internalbf.com/client/pages/ClipChangesPage.tsx
> +import { Table } from "packages/bfDs/BfDsTable.tsx";
np!

2024-08-21 14:52 UTC, justicart approved these changes

2024-08-21 15:01 UTC, merged