Temporary Commit at 8/21/2024, 3:36:44 PM
bolt-foundry/bolt-foundry pull request #451
Opened 2024-08-21 19:37 UTC by mikesavior

Summary: refactoring userland views: Input -> BfDsInput

Test Plan:

2024-08-21 19:56 UTC, justicart requested changes
Remove stray Icon, Table, TableCell files (and make sure they all still work)

2024-08-22 03:26 UTC, mikesavior commented
> Remove stray Icon, Table, TableCell files (and make sure they all still work)

sorry about that- all set!

2024-08-22 16:08 UTC, justicart approved these changes

2024-08-22 19:04 UTC, mikesavior commented
closing to reopen fixed ver after some wrangling commits

2024-08-22 19:04 UTC, closed without merging