add dark mode switch
bolt-foundry/bolt-foundry pull request #481
Opened 2024-08-22 21:39 UTC by justicart

Summary: update ListItem with switch, enable dark mode in settings

Test Plan:

2024-08-22 21:47 UTC, justicart commented
https://github.com/user-attachments/assets/d0212da4-815d-4732-a30c-0077e0f51382

2024-08-23 14:32 UTC, randallb requested changes

2024-08-23 14:32 UTC, randallb commented on packages/client/pages/SettingsPage.tsx
>  export function SettingsPage() {
Can you please use bfDs context instead of doing this in the page? Every example of a context is "use contexts for darkmode" lol

2024-08-23 17:54 UTC, justicart commented on packages/client/pages/SettingsPage.tsx
>  export function SettingsPage() {
updated

2024-08-23 20:11 UTC, merged