get posthog lib loaded somewhere at all to begin developing against it
bolt-foundry/bolt-foundry pull request #533
Opened 2024-08-27 21:13 UTC by mikesavior

Summary: comments throughout

Test Plan:

2024-08-27 21:18 UTC, justicart requested changes

2024-08-27 21:18 UTC, justicart commented on packages/bfDs/BfDsButton.tsx
> -      data-bf-testid={testId}
My fault... can you revert this file?

2024-08-27 21:20 UTC, mikesavior commented on packages/bfDs/BfDsButton.tsx
> -      data-bf-testid={testId}
np, doing some cleanup with it so I gotchu

2024-08-28 00:44 UTC, randallb requested changes
i think an actual test plan (like a screencast / screenshot of what you're trying to achieve) would help me understand what's going on re your comments.

when you say it's only capturing a single event, showing a screen cast of what you're trying and what you're seeing can help everyone understand what's going on,

additionally, my strong preference is to put comments like that in the commit body and not in the actual code since they can get stale very very fast.

check out #532 for an example. that commit was a fundamentally big change, and touched a lot of files, so i was very though in documenting it, just not in code comments which ideally should be less and less necessary with LLMs able to explain code.

2024-08-28 00:44 UTC, randallb commented on packages/events/mod.ts
> +    event: "user signed up",
i would make these more obviously test values... like "test id" and "test event"

2024-08-28 00:44 UTC, randallb commented on packages/events/mod.ts
> +  const posthogId = Deno.env.get("BF_POSTHOG_ID") ?? "";
if you're trying to run this in a browser context it hopefully is throwing an error since you're trying to get an env var.

2024-08-28 14:13 UTC, mikesavior commented on packages/events/mod.ts
> +  const posthogId = Deno.env.get("BF_POSTHOG_ID") ?? "";
I get an env var here- is there a thing I'm missing with what you say here?

2024-08-29 19:05 UTC, closed without merging